# ============================================================================
# make_app_bundle.ps1 - build and upload the app-stack code bundle to S3.
#
# Why a tar and not "git clone" on the node (design v2 section 7 A2):
#   the repo is private, so cloning would mean planting GitHub credentials on
#   the EC2 box. The instance role already has S3 read, so shipping a tar adds
#   zero new credentials. Same reasoning as the GPU stack's make_bundle.sh.
#
# The node needs the whole working tree because our containers bake only the
# dependencies and mount the source (./:/app) - docker-compose.yml itself lives
# in the repo, so an empty /opt/aitch means there is nothing to bring up.
#
# WHAT GOES IN: exactly what git tracks at <Ref>, via 'git archive'.
#   .env, node_modules, .terraform, tfstate are gitignored -> excluded for free.
#   Embedding weights (hf_cache, 4.7GB) are NOT here - they live under their own
#   S3 prefix and the EC2 boot script syncs them into the aitch_hf_cache volume.
#
# WHEN: the bundle is a snapshot of a branch at one moment. Build it on the
#   infra day from whatever 'dev' is then - a bundle built early silently
#   ships without whatever merged afterwards.
#
# Usage (from repo root):
#   .\scripts\make_app_bundle.ps1 -DryRun     # build locally, do not upload
#   .\scripts\make_app_bundle.ps1             # build + upload to S3
#   .\scripts\make_app_bundle.ps1 -Ref HEAD   # bundle the current branch instead
#
# Bucket/key are read from the terraform variables (single source) unless
# overridden with -Bucket / -Key.
# ============================================================================

param(
  [string]$Ref = 'upstream/dev',
  [string]$Bucket = '',
  [string]$Key = '',
  [switch]$DryRun,
  [switch]$Yes
)

$ErrorActionPreference = 'Continue'

$Region   = 'ap-northeast-2'
$RepoRoot = Split-Path -Parent $PSScriptRoot
$InfraDir = Join-Path $RepoRoot 'infra\app-stack'

function Write-Head($text) {
  Write-Host ''
  Write-Host "=== $text ===" -ForegroundColor Cyan
}

function Fail($text) {
  Write-Host "ERROR: $text" -ForegroundColor Red
  exit 1
}

if (-not (Get-Command git -ErrorAction SilentlyContinue)) { Fail 'git not found in PATH.' }
if (-not (Get-Command aws -ErrorAction SilentlyContinue)) { Fail 'aws cli not found in PATH.' }

# ---- bucket / key: read from terraform so there is one source -------------
function Get-TfVar($name) {
  if (-not (Test-Path (Join-Path $InfraDir '.terraform'))) { return '' }
  Push-Location $InfraDir
  try {
    $v = "var.$name" | terraform console 2>$null
    if ($LASTEXITCODE -ne 0) { return '' }
    return ($v -replace '"', '').Trim()
  } finally { Pop-Location }
}

if ([string]::IsNullOrWhiteSpace($Bucket)) { $Bucket = Get-TfVar 'bundle_s3_bucket' }
if ([string]::IsNullOrWhiteSpace($Key))    { $Key    = Get-TfVar 'bundle_s3_key' }
if ([string]::IsNullOrWhiteSpace($Bucket) -or [string]::IsNullOrWhiteSpace($Key)) {
  Fail 'could not resolve bundle bucket/key from terraform (run app_stack.ps1 -Plan once, or pass -Bucket/-Key).'
}

Push-Location $RepoRoot
try {

  # ---- which commit are we shipping? ---------------------------------------
  $sha = git rev-parse --verify "$Ref^{commit}" 2>$null
  if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($sha)) {
    Fail "ref not found: $Ref  (did you 'git fetch upstream'?)"
  }
  $subject = git log -1 --format='%s' $sha
  $when    = git log -1 --format='%cI' $sha

  Write-Head 'bundle source'
  Write-Host ("ref     : {0}" -f $Ref)
  Write-Host ("commit  : {0}" -f $sha.Substring(0, 12))
  Write-Host ("date    : {0}" -f $when)
  Write-Host ("subject : {0}" -f $subject)

  # The bundle is a snapshot, so anything not merged into <Ref> is simply
  # absent on the node - with no error to notice it by. Say so out loud.
  $ahead = git log --oneline "$sha..HEAD" 2>$null
  if ($ahead) {
    $n = ($ahead | Measure-Object).Count
    Write-Host ''
    Write-Host ("WARN: your current branch has {0} commit(s) NOT in {1}:" -f $n, $Ref) -ForegroundColor Yellow
    $ahead | ForEach-Object { Write-Host ("        {0}" -f $_) }
    Write-Host '      Those changes will NOT be on the node. Merge first, or pass -Ref HEAD.' -ForegroundColor Yellow
  }

  # ---- stamp: let the node say what it is running --------------------------
  $stamp = Join-Path ([System.IO.Path]::GetTempPath()) 'BUNDLE_INFO.txt'
  @(
    "ref     : $Ref"
    "commit  : $sha"
    "date    : $when"
    "subject : $subject"
    "built   : $((Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')) UTC"
    "by      : $env:USERNAME@$env:COMPUTERNAME"
    ""
    "This file is generated by scripts/make_app_bundle.ps1."
    "On the node: cat /opt/aitch/BUNDLE_INFO.txt to see which commit is deployed."
  ) | Set-Content -Path $stamp -Encoding utf8

  # ---- build ---------------------------------------------------------------
  $out = Join-Path ([System.IO.Path]::GetTempPath()) 'aitch-app-stack.tar.gz'
  if (Test-Path $out) { Remove-Item $out -Force }

  Write-Head 'git archive'
  # git archive ships ONLY tracked files, so .env / node_modules / .terraform /
  # tfstate are excluded without maintaining a second ignore list.
  git archive --format=tar.gz --add-file="$stamp" -o "$out" $sha
  if ($LASTEXITCODE -ne 0 -or -not (Test-Path $out)) { Fail 'git archive failed.' }

  $mb = [math]::Round((Get-Item $out).Length / 1MB, 1)
  Write-Host ("built: {0}  ({1} MB)" -f $out, $mb)

  if ($DryRun) {
    Write-Host ''
    Write-Host 'dry run - nothing uploaded.' -ForegroundColor Green
    Write-Host ("would upload to: s3://{0}/{1}" -f $Bucket, $Key)
    exit 0
  }

  # ---- upload --------------------------------------------------------------
  $dest = "s3://$Bucket/$Key"
  if (-not $Yes) {
    Write-Host ''
    Write-Host ("About to overwrite {0} ({1} MB)." -f $dest, $mb) -ForegroundColor Yellow
    Write-Host 'The node picks this up on its NEXT boot - a running node keeps what it has.'
    $answer = Read-Host 'Type upload to continue'
    if ($answer -ne 'upload') { Write-Host 'aborted.'; exit 1 }
  }

  Write-Head 'upload'
  aws s3 cp "$out" $dest --region $Region
  if ($LASTEXITCODE -ne 0) { Fail 'upload failed.' }

  # "no exception" is not proof it landed - ask S3 what it has.
  $size = aws s3api head-object --bucket $Bucket --key $Key --region $Region --query 'ContentLength' --output text 2>$null
  if ($LASTEXITCODE -ne 0) {
    Write-Host 'WARN: uploaded but head-object failed - verify manually.' -ForegroundColor Yellow
  } else {
    Write-Host ("verified on S3: {0} bytes" -f $size) -ForegroundColor Green
  }

  Remove-Item $out -Force -ErrorAction SilentlyContinue
  Remove-Item $stamp -Force -ErrorAction SilentlyContinue

  Write-Host ''
  Write-Host 'Next: .\scripts\app_stack.ps1 -Up   (the boot script unpacks this into /opt/aitch)'
  Write-Host 'If the node is ALREADY up, it will not re-download - recreate it or pull the tar by hand.'

} finally {
  Pop-Location
}
